### ISSUE TITLE
review's date returns 'Invalid Date'

### ISSUE THREAD

**Issue by chihara** [facundoolano/google-play-scraper#348]
* Operating System: Ubuntu 16.04.2 LTS
* Node version: v12.10.0
* google-play-scraper version: 7.0.1

### Description: 
One review's date returns 'Invalid Date' . not parsed.

I checked google play store's data. This review has Date data was 1 length array.
```
    [
      "gp:AOqpTOH8ZUv5em6TQwWMbnKqPtEWngJ9Ts-S_PsVycbHvtRhL0qIPRzrO8_TVHodY5-v-0W1GRb3kiObyc9oHw",
      ["K. Bacon",[null,2,null,[null,null,"https://lh3.googleusercontent.com/-bsw62Zcu8JI/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rfRA9WjZvNztK8jPCa2rWsuf99Uyw/photo.jpg"]]],
      4,
      null,
      "概ね良好です。経歴などxxxxxと同期していただければ、有難いです。",
      [1554881170],
      7,
      null,
      null,
      ["101024111675687700835","K. Bacon",null,[[null,2,null,[null,null,"https://lh3.googleusercontent.com/-bsw62Zcu8JI/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rfRA9WjZvNztK8jPCa2rWsuf99Uyw/photo.jpg"]],true],[null,2,null,[null,null,"https://lh3.googleusercontent.com/Yq7oyNIvAAkuc69fG51sbAQS4otJxbObbt3xdr8tXxXyUdq4tVGtfgeKuptveGdP1srxaHVrNPzOYcfaEQ"]]],
      "2.8.1",
      null,
      [[["vaf_never_display_make_you_happy"],["vaf_never_display_content_language"],["vaf_never_display_app_description"]]]
    ]
```

### Example code:
```js
const playStore = require('google-play-scraper');
var requestInfo = {appId: 'jp.co.recruit.rikunabihaken.rikunabihaken', lang: 'ja', country: 'jp'};
playStore.reviews(requestInfo).then(console.log);
```

### Error message:
date is 'Invalid Date'.
```
  {
    id: 'gp:AOqpTOH8ZUv5em6TQwWMbnKqPtEWngJ9Ts-S_PsVycbHvtRhL0qIPRzrO8_TVHodY5-v-0W1GRb3kiObyc9oHw',
    userName: 'K. Bacon',
    userImage: 'https://lh3.googleusercontent.com/-bsw62Zcu8JI/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rfRA9WjZvNztK8jPCa2rWsuf99Uyw/photo.jpg',
    date: 'Invalid Date',
    score: 4,
    scoreText: '4',
    url: 'https://play.google.com/store/apps/details?id=jp.co.recruit.rikunabihaken.rikunabihaken&reviewId=gp:AOqpTOH8ZUv5em6TQwWMbnKqPtEWngJ9Ts-S_PsVycbHvtRhL0qIPRzrO8_TVHodY5-v-0W1GRb3kiObyc9oHw',
    title: null,
    text: '概ね良好です。経歴などxxxxxと同期していただければ、有難いです。',
    replyDate: null,
    replyText: null,
    version: '2.8.1',
    thumbsUp: 7,
    criterias: [ [Object], [Object], [Object] ]
  },
```

**Comment by icarcal** [comment]
@chihara, I just sent the PR #349 to fix this.
Thanks.

**Comment by chihara** [comment]
@icarcal Great! thanks.

**Comment by facundoolano** [comment]
should be fixed in the latest version.

**Comment by chihara** [comment]
@facundoolano Thanks!

**Comment by chihara** [comment]
@facundoolano @icarcal 
I checked in latest version. But not fixed. Date returns null.
This is same data.
```
  {
    id: 'gp:AOqpTOH8ZUv5em6TQwWMbnKqPtEWngJ9Ts-S_PsVycbHvtRhL0qIPRzrO8_TVHodY5-v-0W1GRb3kiObyc9oHw',
    userName: 'K. Bacon',
    userImage: 'https://lh3.googleusercontent.com/-bsw62Zcu8JI/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rfRA9WjZvNztK8jPCa2rWsuf99Uyw/photo.jpg',
    date: null,
    score: 4,
    scoreText: '4',
    url: 'https://play.google.com/store/apps/details?id=jp.co.recruit.rikunabihaken.rikunabihaken&reviewId=gp:AOqpTOH8ZUv5em6TQwWMbnKqPtEWngJ9Ts-S_PsVycbHvtRhL0qIPRzrO8_TVHodY5-v-0W1GRb3kiObyc9oHw',
    title: null,
    text: '概ね良好です。経歴などxxxxxと同期していただければ、有難いです。',
    replyDate: null,
    replyText: null,
    version: '2.8.1',
    thumbsUp: 7,
    criterias: [ [Object], [Object], [Object] ]
  },
```

I think this is cause. please check again.
current
```const millisecondsLastDigits = String(dateArray[1]) || '000';```
correct
```const millisecondsLastDigits = String(dateArray[1] || '000');```

**Comment by icarcal** [comment]
This is my bad.
I made a last minute change that introduced the bug again.

Just sent the #355 to fix it again.

Thanks for the report @chihara

**Comment by chihara** [comment]
@icarcal Thanks :)
